apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-ui

spec:
  rules:
    - host: ui.example.com
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name:  guestbook-ui
                port:
                  number: 80
